services:
    caddy:
        container_name: rafalbrauner-caddy
        build:
            context: .
            dockerfile: ./docker/caddy/Dockerfile
            target: prod
            network: host
            args:
                TZ: ${TZ:-Europe/Warsaw}
                USER: ${APP_USER:-app}
                GROUP: ${APP_GROUP:-app}
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        restart: unless-stopped
        working_dir: /var/www/html
        # user: "${UID:-1000}:${GID:-1000}"
        networks:
            shared-network:
        volumes:
            - caddy-data:/data
            - caddy-config:/config
            # - shared-home:/home/${APP_USER:-app}
            - .:/var/www/html
        labels:
            traefik.enable: true
            traefik.http.services.rafalbrauner.loadbalancer.server.port: 80
            traefik.http.services.rafalbrauner-secure.loadbalancer.server.port: 443
            traefik.http.routers.rafalbrauner.rule: Host(`${DOMAIN:-rafalbrauner.com}`)
            traefik.http.routers.rafalbrauner.entrypoints: http
            traefik.http.routers.rafalbrauner.tls: false
            traefik.http.routers.rafalbrauner.service: rafalbrauner
            traefik.http.routers.rafalbrauner-secure.rule: Host(`${DOMAIN:-rafalbrauner.com}`)
            traefik.http.routers.rafalbrauner-secure.entrypoints: https
            traefik.http.routers.rafalbrauner-secure.tls: true
            traefik.http.routers.rafalbrauner-secure.service: rafalbrauner-secure

    php:
        container_name: rafalbrauner-php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            target: prod
            network: host
            args:
                TZ: ${TZ:-Europe/Warsaw}
                USER: ${APP_USER:-app}
                GROUP: ${GROUP:-app}
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        restart: unless-stopped
        working_dir: /var/www/html
        user: "${UID:-1000}:${GID:-1000}"
        networks:
            shared-network:
        volumes:
            - shared-home:/home/${APP_USER:-app}
            - .:/var/www/html

    node:
        container_name: rafalbrauner-node
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
            target: prod
            network: host
            args:
                TZ: ${TZ:-Europe/Warsaw}
                USER: ${APP_USER:-app}
                GROUP: ${APP_GROUP:-app}
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        restart: unless-stopped
        working_dir: /var/www/html
        user: "${UID:-1000}:${GID:-1000}"
        tty: true
        networks:
            shared-network:
        volumes:
            - shared-home:/home/${APP_USER:-app}
            - .:/var/www/html

networks:
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
    caddy-data:
        name: rafalbrauner-caddy-data
    caddy-config:
        name: rafalbrauner-caddy-config
